# Additions to the existing configuration.yaml

homeassistant:

  packages:
    pyscript: !include pyscript/config.yaml


# Sensor that is populated by all items on the shopping list
command_line:
  - sensor:
      name: shoppinglist
      command:   echo "{\"list\":" $( cat .shopping_list.json) "}" 
      value_template: > 
        {{ value_json.list | length }}
      json_attributes:
        - list   